### ISSUE TITLE
SelectFiltered: Wrong keyboard navigation

### ISSUE THREAD

**Issue by gabriellsh** [RocketChat/Rocket.Chat.Fuselage#162]
**Description**
Choosing an option with the arrow keys selects the wrong one when filter is applied.

**Steps to reproduce**
Open select, filter results, select option with keyboard and press enter.

**Insert an image/gif**

![Select keyboard filter bug](https://user-images.githubusercontent.com/40830821/76116268-72a90980-5fc8-11ea-81e3-05fb930a4877.gif)

**Comment by TaimurAzhar** [comment]
Hello, I think I have solved this issue. Creating the PR currently. It took me a while.

**Comment by dougfabris** [comment]
Fixed here: #169
