### ISSUE TITLE
Why can't I see any documentation describing how the component is used?

### ISSUE THREAD

**Issue by PluviaCon** [RocketChat/Rocket.Chat.Fuselage#267]
I'm surprised you all use this component.
If anyone knows, please let me know. Thank you.

**Comment by ggazzo** [comment]
https://rocketchat.github.io/Rocket.Chat.Fuselage/?path=/story/box-intro--page

**Comment by ggazzo** [comment]
thanks for your interest in our fuselage framework... nowadays we keep the documentation for components under storybook
![image](https://user-images.githubusercontent.com/5263975/88396430-e6da2300-cd98-11ea-93a6-da00b80e2deb.png)


and there is some Readme files under each package

https://github.com/RocketChat/Rocket.Chat.Fuselage/tree/develop/packages/fuselage-hooks
https://github.com/RocketChat/Rocket.Chat.Fuselage/tree/develop/packages/css-in-js

**Comment by ggazzo** [comment]
any problem let me know :)
