### ISSUE TITLE
Edit profile status buttons could use some padding

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Fuselage#338]
Edit profile status buttons could use some padding

<img width="639" alt="Screen Shot 2020-11-30 at 10 11 20 PM" src="https://user-images.githubusercontent.com/6295044/100699731-fd9d1180-3358-11eb-807f-6247fc88fd9f.png">

**Comment by YohanTz** [comment]
Hi ! I see that this issue is still pending, can I work on it ? 😄

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/119182937-40969280-ba28-11eb-9dad-2fdb7f2f9407.png)

This has been resolved.
