### ISSUE TITLE
Menu: Closing menu by clicking the 3 dot meu doesn't occur

### ISSUE THREAD

**Issue by sk044** [RocketChat/Rocket.Chat.Fuselage#409]
### Description:
Related to [Rocket.Chat #20968](https://github.com/RocketChat/Rocket.Chat/issues/20968)
Closing menu by clicking the 3 dot meu doesn't occur 

### Steps to reproduce:

1. Go to a particular channel
2. Click on the 3 dot menu on the top right corner 

### Expected behavior:

After expanding menu , by clicking the three dot menu should close 

### Actual behavior:

The above doesn't happen and closes after clicking anywhere else .

![109752845-26a69a00-7c07-11eb-9435-2ed86b9c4fbd](https://user-images.githubusercontent.com/54908788/109836420-24295c00-7c6a-11eb-8a50-71bc326ddceb.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  12.18.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Relevant logs:

**Comment by sk044** [comment]
Currently working on it .

**Comment by ABHAYJAIN2601** [comment]
@sk044 did you solve this issue?

**Comment by im-adithya** [comment]
Hey @sk044 and @ABHAYJAIN2601! This has already been filed as #388 and will be fixed by #389

**Comment by sk044** [comment]
> Hey @sk044 and @ABHAYJAIN2601! This has already been filed as #388 and will be fixed by #389

Ohh nice , is it solved as of now??

**Comment by im-adithya** [comment]
Yes, it just has to get merged.
