### ISSUE TITLE
UI kit

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.Fuselage#96]
# Components
- [x] IMAGE
- [x] BUTTON
- [x] STATIC_SELECT
- [x] MULTI_STATIC_SELECT
- [ ] CONVERSATION_SELECT
- [ ] CHANNEL_SELECT
- [ ] USER_SELECT 
- [x] OVERFLOW 
- [x] DATEPICKER
- [x] PLAIN_TEXT_INPUT
- [x] SECTION
- [x] DIVIDER
- [x] ACTIONS
- [x] CONTEXT
- [x] INPUT

# FEATURES
- [x] export interfaces to help different implementations
- [ ] Loki regression

**Comment by machester4** [comment]
I would like to take any of these. Is there any way to get a clearer idea of ​​how each component would look? Do you use Figma?

**Comment by brunosquadros** [comment]
@machester4 Yes, We are creating a repository of our components on Figma. 
We're planning to share it in the next 2 or 3 weeks. 
As soon as it is available we let you know 👊 
Cheers!

**Comment by ggazzo** [comment]
hey @machester4 I'm afraid we already released all the mentioned components 😢
